### ISSUE TITLE
Minify html

### ISSUE THREAD

**Issue by leowzukw** [zoggy/stog#19]
It would be great to minify produced html, to improve loading time.

[Here is a set of tool.](http://getawesomeness.com/get/wpo#minifiers-html)

**Comment by zoggy** [comment]
Since generated files are static, you can always applied one of these tools on the generated files. But I agree that a simple plugin calling such a tool could be useful and simplify the compilation process of a site.

Such a plugin could act the following way, for each document:
- dump the xml resulting of the computation of the document,
- apply an external tool (maybe with an option to give a different command than the default one),
- load the resulting xml file.

In fact, such a plugin could be more general to allow the application of any external tool on the current XML of each document.

I'll think about this. Thanks for the suggestion.

**Comment by leowzukw** [comment]
Great!

However, to keep pure-ocaml functionnality, the library you use is maybe able to write "ugly" xml, a bit like [YoJSON](http://mjambon.com/yojson.html) with

``` ocaml
val to_string : ?buf:Bi_outbuf.t -> ?len:int -> ?std:bool -> json -> string
Write a compact JSON value to a string.
```

**Comment by zoggy** [comment]
I just added a new  `stog.extern` plugin.Use it as any other stog plugin. Here is an example of configuration file (`.stog/config-extern`):
````json
{
  "actions": [
     { name:"cat", types: ["post", "page"], command: "cat" }
    ]
}
````
Here we define a single action named `cat`, that will apply the `cat` command on documents of type `post` or `page`. The command will be given on stdin the current XML body of each document and must output the result to stdout. To define when this is done, you must give a level for the action `cat` in your `.stog/config` file, in variable `levels`:
````json
{
  ...
  levels: [
    { module: "extern", levels: [ ("cat", [1000]) ] }
  ]
}
````
This will be part of the next release. Note that in this release, configuration files will be in JSON syntax instead of ocaml-ish syntax.

**Comment by leowzukw** [comment]
Thanks!

**Comment by zoggy** [comment]
About a pure-ocaml function to do this, compaction is not that easy, as it supposes to know about the semantics of the XML tags, because spaces must not be modified in tags like `<pre>` but also in any tag that will have a css style setting a `<pre>`-like behaviour. So I prefer letting the user use the command which is best in her context.

And by the way, minifying html pages will not result in big compaction. If it is a problem, you may use a server doing some compression on the fly.
