### ISSUE TITLE
Where's the template for page elements (page.tmpl)?

### ISSUE THREAD

**Issue by pveber** [zoggy/stog#27]
I'm making my first steps with stog, after having generated an initial website following the 5-minute tutorial, I wanted to modify the template for page elements, but it seems it was not generated:
```sh
$ ls site/.stog/templates/
by-month.tmpl  doc-in-list.tmpl  post.tmpl  rss-item.tmpl  rss.tmpl
```
I assume there's a default value that is used internally. Is there a way to generate the corresponding `page.tmpl`?

**Comment by zoggy** [comment]
Indeed, the tutorial must be updated. The page template is located in the `share/stog/templates` directory of you ocaml installation. For example with opam and ocaml-4.02.3, it is in 
`~/.opam/4.02.3/share/stog/templates/`.

You can copy the file to your `site/.stog/tempates` directory and change it. It will be used instead of the default one.

**Comment by pveber** [comment]
Alright, that worked perfectly, thanks a lot! I'm trying to keep some notes of the details I couldn't find easily from the current documentation. Maybe that could help to update it.

**Comment by zoggy** [comment]
Do not hesitate to post your notes in an issue so that I can update the documentation, or make a PR :)

**Comment by leowzukw** [comment]
I think my issue is quite related to this one, that's why I post it here.

After some investigation, both in `share/stog` directory and on the website, I couldn't find the template in which we use the image `rss.png`. I would like to replace it by a font awesome icon.

Where is it? Or is hard-coded?

**Comment by zoggy** [comment]
Indeed it is hard-coded, by now :-( . I will have to think about a way to specify something else, maybe by handling some site-wide definition.

**Comment by leowzukw** [comment]
Ok, thanks for your quick-answer.

**Comment by zoggy** [comment]
This commit allows you to specify a template for document lists: https://github.com/zoggy/stog/commit/569de6b7011558cdae7575b2325abcde4b3df56b . The default template is the same as the previously hard-coded one.

**Comment by leowzukw** [comment]
Great, thanks!
